= from ZERO to Gradle HERO image:https://travis-ci.org/daggerok/from-zero-to-gradle-hero.svg?branch=master["Build Status", link="https://travis-ci.org/daggerok/from-zero-to-gradle-hero"]

//tag::content[]
- **Gradle best practises** -- Idiomatic gradle separation of concerns - splitting task configuration by it's bounded context. see `build.gradle` and `garadle/*.gradle` files
- **Ascii documentation conversion to HTML5 and PDF formats**
- **Gradle JUnit 5 native support** configuration example: `gradle/junit.gradle`
- **selenide easy end-to-end tests**
- **Sexy Allure reports** configuration example: `gradle/allure.gradle`
- **JaCoCo code coverage** configuration example: `gradle/jacoco.gradle`
- **and many more!**

This is a simple spring-boot WebFlux Kotlin app.
Yet another spring-boot | kotlin | webflux example: `src/main/kotlin/daggerok/webflux/WebfluxConfig.kt`
Just for fun, for this app I'm building HTML page from asciidoc (see gradle task `distDoc` in
`gradle/distribution/distribution.adoc`) and serving result using awesome `spring-webflux`

[source,bash]
----
./gradlew -S clean dist
unzip ./dist/from-zero-to-gradle-hero-0.0.1.zip -d ./dist
ls -lah ./dist/from-zero-to-gradle-hero/

npm i -g serve

serve ./dist/from-zero-to-gradle-hero/html5/
open http://localhost:5000/documentation.html

serve ./dist/from-zero-to-gradle-hero/pdf/
open http://localhost:5000/documentation.pdf
----

[source,bash]
----
./gradlew -S clean build :jacocoTestReport :allureReport

npm i -g serve

serve ./build/jacoco/html/
open http://localhost:5000

serve ./build/reports/allure-report
open http://localhost:5000
----

////
.gradle / docker-compose
[source,bash]
----
./gradlew
java -jar build/libs/*.jar
bash build/libs/*.jar

./gradlew build composeUp
./gradlew composeDown
----

.maven / docker-compose
[source,bash]
----
./mvnw
java -jar target/*.jar
bash target/*.jar

./mvnw; ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up
./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down
----
////

generated by link:https://github.com/daggerok/generator-jvm/[jvm] yeoman generator
//end::content[]
